imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

mink:
    browser_name: firefox
    default_session: selenium2
    selenium2:
        #wd_host: http://server:4444/wd/hub
        wd_host: http://localhost:4444/wd/hub
    base_url: %test_base_url%
    #base_url: http://localhost/kata-bowling/web/app_test.php
