# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

#SrosatoBowlingBundle:
#    resource: "@SrosatoBowlingBundle/Controller/"
#    type:     annotation
#    prefix:   /

srosato_bowling_game:
    type:     rest
    resource: Srosato\BowlingBundle\Controller\GameController

